export { default as main } from './MainReducer'
export { default as term } from './termReducer'
export { default as comment } from './commentReducer'
export { default as chart } from './chartReducer'
export { default as publication } from './publicationReducer'
export { default as monitoring } from './monitoringTermReducer'
export { default as conversation } from './conversationReducer'