package ma.octo.smap.web;

import ma.octo.smap.persistance.domains.WebData;
import ma.octo.smap.persistance.domains.WebData_ar;
import ma.octo.smap.persistance.domains.WebData_fr;
import ma.octo.smap.services.MonitoringService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Date;
import java.util.List;

import static org.springframework.http.HttpStatus.OK;
import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

/**
 * Created by adib on 17/04/17.
 */
@RestController
@RequestMapping(value = "/api")
public class MonitoringApiController {

    private final MonitoringService monitoringService;

    public MonitoringApiController(MonitoringService webDataService) {
        this.monitoringService = webDataService;
    }


    @RequestMapping("/webdata/save")
    public void webData() {

        String data1_title_ar = "اللورد آندرو بارملي: المغرب سيتحول إلى مركز مالي إقليمي قوي";
        String data2_title_ar = "المحمدية وإفلاس \"سامير\" .. رزء اقتصادي يوازي القلق الاجتماعيّ";
        String data3_title_ar = "ماروبيني اليابانية تلتحق بالقطب المالي للبيضاء";
        String data4_title_ar = "تقرير بحثي: أكبر مصرفيي العالم يمارسون الإرهاب المالي";
        String data5_title_ar = "موثقو المغرب يطالبون بالقطع مع التقادم في تزوير وثائق العقارات";
        String data6_title_ar = "البورصة تراكم الخسائر وذهول صغار المستثمرين";
        String data7_title_ar = "اتفاق يجنّب شركة الطيران أليطاليا شبح الإفلاس";
        String data8_title_ar = "احتياطي النقد الأجنبي يحافظ على ارتفاعه بالمغرب";
        String data9_title_ar = "التجاري وفابنك و فيزا يوزعان جوائز كأس إفريقيا";
        String data10_title_ar = "سلوى أخنوش تنال جائزة إفريقيّة لسيدات المقاولات";

        String data1_body_ar = "أثنى اللورد البريطاني عمدة الحي المالي لمدينة لندن، آندرو بارملي Andrew Parmley، على أداء الاقتصاد الوطني وكبريات الشركات المغربية، مؤكدا أنه متفائل بأن المغرب سيتحول إلى مركز مالي إقليمي قوي في السنوات القادمة. وأوضح آندرو بارملي، في مؤتمر صحافي مصغر نظمه يوم الأربعاء بمدينة الدار البيضاء، أن القطب المالي للدار البيضاء يتوفر على كافة الإمكانيات التي تجعله من المراكز المالية التي تتوفر على مؤهلات كبيرة، والتي تستقطب اهتمام المجموعات المالية البريطانية. وأضاف عمدة الحي المالي لمدينة لندن، الذي يقوم بزيارة إلى المغرب ما بين 11 و13 أبريل 2017، أنه عقد لقاءات مع مجموعة من المسؤولين المغاربة في المجال المالي والصناعي، ووقف شخصيا على مجموعة من قصص النجاح التي حققها البعض منهم، كما في المجمع الشريف للفوسفاط. وقال بارملي: \"تابعنا عن كثب كيف تمكن المجمع الشريف للفوسفاط من رفع مستوى أداء سلاسله الإنتاجية، من خلال الرفع من المردودية في ظل التحكم في كلفة الإنتاج، مع التركيز على تحويل الفوسفاط، وهذا يجعلنا نأمل أن تشارك بريطانيا في تحقيق مزيد من النجاح بالنسبة لهذه المجموعة التي توجد في المغرب، الذي يتوفر على أكبر احتياطيات الفوسفاط في العالم\". وأكد اللورد بارملي أن خروج بريطانيا من الاتحاد الأوروبي لن يعيق التعاون المغربي البريطاني، مضيفا: \"بريطانيا شريك أساسيا للمغرب، وسنواصل التعاون الاقتصادي، مع تعزيزه بشكل متزايد.";
        String data2_body_ar = "سلطت ندوة بمدينة المحمدية الضوء على أزمة شركة \"سامير لتكرير البترول\"، المتوقفة عن الإنتاج منذ غشت 2015، ودخول ملفها القضاء، حيث تم إصدار قرار بتصفيتها. وكشف الحسين اليماني، الكاتب العام للنقابة الوطنية لصناعة البترول والغاز، أن من أسباب عجز الشركة وإفلاسها أنها لم تكن تتوفر على دراسات حول مخاطر تقلب الأسعار، إلى جانب عدم قيام السلطات المغربية بمراقبة أداءها؛ ناهيك عن تقصير منتدبي الحسابات وبنك المغرب. وسجل المسؤول النقابي، في الندوة التي نظمت تحت شعار\"توقف مصفاة المحمدية: الخسائر والآفاق\"، مساء أمس الخميس، تراجعا فظيعا في مستويات الاحتياط الأمني من المواد البترولية، وصل إلى أقل من أسبوع من مادة الفيول لإنتاج الكهرباء، إلى جانب النقص الخطير في الطاقة الوطنية للتخزين، بعد تعطيل خزانات المصفاة التي توفر ثلاثة أشهر من الاستهلاك الوطني. وأكد اليماني، في معرض مداخلته، أن توقف المصفاة أدى إلى \"فقدان الاقتصاد الوطني للقيمة المضافة لصناعة التكرير على حساب توفر العملة الصعبة\"، مضيفا أنه يهدد بإتلاف الرأسمال اللامادي الذي تمثله 50 سنة من الخبرة. وأشار عضو الجبهة النقابية، في معرض حديثه عن الخسائر التي تنتج عن توقف المصفاة، إلى كونها تؤثر في نسبة 10% من ساكنة مدينة المحمدية، التي باتت مهددة في مصدر عيشها، كما أدت إلى حرمان المدينة من الرواج التجاري الناجم عن صرف ما يقارب مليار سنتيم سنويا من الأجور والخدمات. ودعا اليماني إلى \"التعجيل بتفويت المصفاة حفاظا على مصالح العباد والبلاد\"، وعودة الدولة إلى المساهمة فيها، إلى جانب الاستئناف العاجل للإنتاج وحماية مصالح العمال، مشددا على ضرورة تأسيس الوكالة الوطنية لتقنين ومراقبة التزويد بالمواد البترولية، والحرص على توفير الاحتياط الأمني ومراجعة القوانين التنظيمية. من جهته، أكد الخبير الاقتصادي المهدي فقير أن هناك إشكالا كبيرا يتعلق بالتخزين، مشيرا إلى أن الفاعلين المغاربة غير قادرين على ذلك، وإلى أن شركة \"سامير\" شكلت صمام أمان للمغرب.ولفت فقير إلى أن \"أي مستقبل للشركة يجب أن يأخذ دروس الماضي بعين الاعتبار، خصوصا في التدبير، لكونها لم تكن تتوفر على ضمانات لأسعار السوق\".وشدد الباحث الاقتصادي في مداخلته، وهو يتحدث عن الجانب المالي والمحاسباتي للشركة، على أنها \"كانت تسير من طرف لجنة تراكم عددا من المهام والتكليفات جد المتناقضة\"، معتبرا أن هذا الأمر \"مستحيل ويفسر عددا من الأخطاء الفادحة؛ ما جعلها تلجأ إلى الاستدانة.";
        String data3_body_ar ="قال مسؤولون عن \"كازا فينانس سيتي\" إن اهتمام المجموعات الاستثمارية بالمغرب ارتفع بشكل لافت منذ بداية العام الحالي، مؤكدين أن آخر الشركات العالمية التي قررت الالتحاق بهذا المركز المالي الإقليمي هي مجموعة \"ماروبيني Marubeni corporation\" اليابانية ذائعة الصيت. وقالت مصادر هسبريس إن المجموعة الاستثمارية اليابانية قررت جعل القطب المالي للدار البيضاء منصة لتعزيز أنشطتها بإفريقيا الغربية، لتصبح الشركة اليابانية الأولى التي تحظى بعلامة CFCA بالمغرب. فونيا كوكوبو، الرئيس التنفيذي لشركة \"ماروبيني\"، قال: \"سيكون للتواجد في القطب دور مهم في ميدان تنمية الفرص الواعدة تجاريا بإفريقيا، خصوصا في ميدان البنية التحتية للمشاريع الصناعية والتوزيع\". من جهته أكد سعيد الإبراهيمي، المدير العام للقطب المالي للدار البيضاء، أن دخول المجموعة اليابانية يشكل مرحلة هامة على مستوى التعاون الاقتصادي والمالي بين المجموعات الاستثمارية اليابانية والمغربية، معبرا عن تفاؤله بإمكانية دخول مزيد من الشركات الاستثمارية اليابانية. ويتيح القطب المالي للدار البيضاء مجموعة من التسهيلات للشركات، منها تسهيل مساطر عقود العمل وحصول الموارد البشرية الأجنبية على بطاقة الإقامة بالمغرب، إلى جانب تسهيلات في ميدان مراقبة التبادل التجاري والتحفيزات الجبائية. وتعمل شركة ماروبيني كوربورايشن Marubeni corporation في مجال التجارة والاستثمار، وتتمثل عملياتها التجارية أساسا في ميدان الاستيراد والتصدير للعديد من المنتجات، منها المواد الغذائية والنسيج والورق والمواد الكيماوية والطاقة والمعادن وكذا آليات النقل. ويمتد نشاط المجموعة الاستثمارية اليابانية إلى الكهرباء والبنيات التحتية والتجهيز الصناعي والمعاملات المالية، وكذا صناعة الإعلام، إلى جانب الإنعاش العقاري والبناء. بينما القطب المالي للدار البيضاء هو شركة مساهمة خاضعة للقانون الخاص، وهي ثمرة لشراكة بين القطاعين الخاص والعام تم إنشاؤها سنة 2010.";
        String data4_body_ar = "أماط تقرير جديد لمركز البحوث العالمية اللثام عن مدى تأثير المصارف على بلدان العالم بأسره، وكيف باتت تتخذ القرارات الكبرى عبر العالم، قائلا إن أكبر مصرفيي العالم \"يمارسون إرهاب المال\"، إضافة إلى ما ترتب عن نظام الخوصصة الذي أبان عن فشله في جل بقاع المعمور مستدلا بحالة الهند. ويقول التقرير إن بذور الوضع الاقتصادي الحالي في الهند زرعت من قبل الرئيس الأربعين للولايات المتحدة الأميركية رونالد ريغان، الذي نفذ إصلاحات اقتصادية معتقدا بأن السياسات الضريبية التي تعود بالنفع على الأثرياء سوف تخلق تأثيرا \"ضعيفا\" على الفقراء، وصفها منتقديه بأنه \"اقتصادات هزيلة\" أو اقتصاديات \"الفودو\" المعروفة أيضا باسم \"ريغانوميكس\". وحسب التقرير، يقوم هذا النظام على خفض الإنفاق على القطاعات الاجتماعية للاقتصاد، ومنع العمال من المطالبة بأجور أعلى حتى من خلال النشاط النقابي، وخفض معايير السلامة والصحة للعاملين؛ وهي السياسة التي اعتمدها الروس، وكانت تعرف باسم \"غلاسنوست وبيريسترويكا\"، أي ما \"التحرير والخصخصة\" إبان فترة موت الاتحاد السوفيتي. وقد صدرت تلك السياسات منذ ذلك الحين إلى بقية العالم، وقد تبنتها النخب السياسية والاقتصادية في كثير من البلدان.ويؤكد المصدر نفسه أن السياسة المتبعة \"دمرت كل البلدان التي اعتمدتها\"، مستدلا في هذا الإطار بالفضائح التي تورط فيها هارشاد مهتا في الهند، ومخططات الهرمية في ألبانيا، وانهيار بنك الاعتماد والتجارة الدولي، وانهيار المنازل الأمنية في اليابان وبريطانيا.ويتحدث التقرير عن كيف أن النظام المعتمد من قبيل عدد من بلدان العالم أدى إلى نوع جديد من الخدمات المصرفية المعروفة الآن باسم \"نموذج المنشأ والتوزيع\".ومن الناحية التاريخية، استخدمت البنوك ودائع لتمويل القروض التي احتفظت بها بعد ذلك في ميزانياتها العمومية حتى تاريخ استحقاقها. وبموجب هذا المبدأ الجديد، لم يعد البنك مؤسسة تركز على أخذ الودائع وتقديم القروض. وبدلا من ذلك، أصبحت تمول بشكل تنافسي وتسعى إلى تحقيق أقصى قدر من الرسوم والعمولات. وبدأت الأبناك تقرض الأشخاص الذين يجدون صعوبة في تمويل ديونهم عن طريق ضمانات كالسكن أو غيرها، وحينها انطلقت مسألة بيع الرهون السكنية التي باتت تعتبر كأسهم قابلة للتداول من قبل البنوك، انطلاقا من وول ستريت وصولا إلى مختلف المناطق.ويصف التقرير النظام المصرفي المعتمد، منذ ذلك الحين، بـ\"الإرهاب المالي\"، مستدلا في هذا الإطار بمقولة لأحد كبار الأدباء يقول فيها: \"أكبر مصرفيي العالم الذين يمارسون إرهاب المال هم أكثر قوة من ملوك العالم والمارشالات؛ بل هم أكثر قوة من بابا روما نفسها، لا يقومون بتوسيخ أيديهم، لا يقتلون أحدا، وكل ما يقومون به هو التصفيق للعرض..\".ويضيف \"هؤلاء التكنوقراط الدوليون يحكمون بلداننا، وهم ليسوا رؤساء ولا وزراء؛ بل حتى لم يتم انتخابهم؛ لكنهم يقررون مستوى المرتبات والإنفاق العام والاستثمارات وحتى مستويات الأسعار وأسعار الفائدة والإعانات بل أيضا معدلات تهاطل الأمطار ومع ذلك، فإنهم لا يهتمون بالسجون أو غرف التعذيب أو معسكرات الاعتقال أو مراكز الإبادة، على الرغم من أن هذه المنازل هي عواقب حتمية أوكتو تيكنولوجي لأفعالهم بل يعتبرون أنفسهم محايدين.";
        String data5_body_ar = "اعتبر عبد اللطيف يكو، رئيس المجلس الوطني لهيئة الموثقين بالمغرب، أن وقف نزيف عمليات الاستيلاء على أملاك الغير، التي شهدت تزايدا كبيرا في السنوات الأخيرة بالمغرب، يتطلب تشديد العقوبات الزجرية المنصوص عليها في القانون المغربي والتخلي عن نظام التقادم المعمول به حاليا بالنسبة إلى التزوير في وثائق ملكية العقارات المحفظة. وقال يكو، في تصريح لهسبريس، إنه \"لا يسع مهنيي مجال التوثيق إلا المطالبة بوقف العمل بنظام التقادم في عمليات التزوير التي تنصب على عقود بيع وشراء العقارات، لأنها تمس بمبدأ حماية الملكية التي يحميها الدستور المغربي في بنده الخامس والثلاثين\". وشدد رئيس المجلس الوطني لهيئة الموثقين بالمغرب على أن حماية حق الملكية يتطلب حماية حق المالك الأصلي، مضيفا: \"يجب إيجاد حل قانوني لقطع الطريق أمام تلك الجهات التي تعمد إلى تزوير وثائق الملكية العقارية للسطو على الممتلكات والأراضي المحفظة، مستغلة ثغرة قانونية تتيح لهم الاحتفاظ بهذه العقارات بعد مرور 4 سنوات من وقوع عملية التزوير، بحكم التقادم. وأضاف أن إلغاء نص تقادم عمليات التزوير للاستيلاء على عقارات المغاربة، سواء تعلق الأمر بالمغاربة المقيمين في الخارج أو الداخل، هو السبيل الوحيد لحماية دستورية الملكية، التي لا يمكن أن يتقادم حقها بأي سبب من الأسباب. وتشير المادة الثانية من الظهير رقم 1.11.178 الصادر في 22 نونبر 2011، والقاضي بتنفيذ القانون رقم 39.08 المتعلق بمدونة الحقوق العينية، إلى حجية الرسوم العقارية وما تتضمنه من تقييدات تابعة لإنشائها تحفظ الحق الذي تنص عليه وتكون حجة في مواجهة الغير على أن الشخص المعين بها هو فعلا صاحب الحقوق المبينة فيها. وعلق عبد اللطيف يكو على هذا الأمر بقوله: \"يجب إيجاد نظام يتيح للمالك الأصلي استعادة عقاره، وتعويض المالك الجديد حسن النية من صندوق ضمان تأميني عن المبالغ التي قام بتأديتها، مع تشديد العقوبات السالبة للحرية والعقوبات المالية على الأشخاص الذين يقفون وراء عمليات التزوير الاستيلاء على عقارات ليست في ملكيتهم.";
        String data6_body_ar = "واصلت بورصة الدار البيضاء مراكمة مزيد من الخسائر خلال العام الجاري، بعد تراجع الأداء السنوي لكل من مؤشر الماديكس بنسبة 4.37 في المائة والمازي 3.62 في المائة. ووضع هذا التراجع الكبير للأداء العام للبورصة حدا لكافة الأرباح التي حققتها سوق الأسهم المغربية في السنة الماضية، في ظل توقعات المحللين التي تشير إلى أنه أداء البورصة سيواصل تراجعه على المنوال نفسه؛ وهو ما لا يخدم مصالح صغار المستثمرين الذين تضررت كثيرا من هذا الانخفاض. التحاليل السوقية، التي أنجزها محللون من كريدي دومارك كابيتال، أشارت إلى أن الربع الثاني من السنة الجارية لن يكون أفضل حالا من الربع الأول، حيث سيعاني سوق الأسهم من عدم استقرار في الأداء. وعبر المحللون عن عدم إلمامهم بكافة العوامل التي تقف وراء هذا التراجع الذي اعتبروه أنه يظل غير منطقي بالنظر إلى الأداء العام الإيجابي لأغلب الأسهم المدرجة في بورصة الدار البيضاء. وقال المحللون: \"البورصة خسرت كافة الأرباح التي حققها العام الماضي، بعد مواصلة تحقيقها لنتائج سلبية أثرت على الأداء العام للسوق\".وتأتي هذه التوقعات المتشائمة حول مستقبل بورصة الدار البيضاء في ظل تسجيل تراجع عام في أداء معظم الأسهم المغربية، حيث تراجع أداء قطاع الخدمات بنسبة 6.85 في المائة بينما انخفض المؤشر العام لقطاع التوزيع بنسبة 6.35 في المائة.وانخفضت مؤشرات الشركات العاملة في قطاع التأمين بنسبة 5.87 في المائة، في الوقت الذي ارتفعت فيه مؤشرات قطاع الصناعات الغذائية بنسبة 0.93 في المائة، والمناجم بنسبة 0.86 في المائة.ولم تتجاوز القيمة الإجمالية لتداولات الجمعة 608 ملايين درهم، لتستقر رأسملة  اتصالات المغرب البورصة في مستوى 566 مليار درهم.";
        String data7_body_ar = "أفلتت شركة الطيران الإيطالية أليتاليا من الإفلاس بصعوبة بعد أن توصلت في ساعة مبكرة من يوم الجمعة إلى اتفاق مع نقابات العمال يمهد الطريق أمام إعادة رسملة الشركة، شريطة ضرورة موافقة العاملين بها على الصفقة. ولم تحقق أليتاليا أي أرباح منذ عام 2002، وهذه هي ثالث مرة تقف فيها شركة الطيران الإيطالية على حافة الإفلاس منذ عام 2007. وكشفت دراسة أجرتها مؤسسة \"ميديابانكا\" المصرفية أن استمرار عمل أليتاليا كلف دافع الضرائب الإيطالي 7.4 مليار يورو (7.85 مليار دولار) خلال الفترة من 1974 حتى 2014. وفي إطار الاتفاق الذي تم التوصل إليه بوساطة من الحكومة الإيطالية الليلة الماضية، وافقت النقابات على تخفيض رواتب الموظفين بنسبة 8 بالمئة في المتوسط، وتسريح 980 شخصا من إجمالي قوة العمل بالشركة والتي تبلغ 12500 شخص. وكانت أليتاليا تقترح في الأساس خفض الرواتب بنسبة 30 بالمئة وتسريح قرابة 2000 موظف. ومن المقرر عرض شروط الاتفاق على العاملين بالشركة خلال استفتاء مزمع الأسبوع المقبل. وكان حملة الأسهم بشركة أليتاليا والجهات الدائنة قد أعلنوا أنهم سوف يحجبون حزمة مساعدات إنقاذ عن الشركة بقيمة ملياري يورو ما لم يتم التوصل إلى اتفاق لخفض نفقات الشركة. وتم خصخصة شركة أليتاليا عام 2008 بعد تلقيها حزمة مساعدات انقاذ سخية من الدولة. وأصبحت شركة طيران الاتحاد الاماراتية عام 2014 أكبر حملة الأسهم في أليتاليا بحصة تبلغ 49 بالمئة، ولكنها فشلت في إنعاش الشركة. وتم الكشف الشهر الماضي عن آخر الخطط الرامية لإنقاذ أليتاليا وهي الوصول لنقطة التساوي بين الأرباح والخسائر بحلول عام 2019. وقال وزير العمل الإيطالي كارلو كاليندا في تصريحات لإذاعة راي الحكومية الإيطالية: \"هذا هو أفضل حل ممكن بالنظر إلى الأزمة التي تمر بها الشركة\". وتتمثل المشكلة الرئيسية بالنسبة لشركة أليتاليا في خسارة مجالات العمل في الرحلات المحلية أمام المنافسين الأرخص سعرا وخدمات القطارات فائقة السرعة، دون أن تنجح في شق طريقها إلى سوق الرحلات طويلة المدى الأكثر ربحية. ويرى كثير من المعلقين ضرورة أن تندمج أليتاليا مع إحدى الشركات المنافسة لها أوكتو تيكنولوجي من أجل ضمان فرصها في الاستمرار.";
        String data8_body_ar = "أعلن بنك المغرب أن صافي الاحتياطيات الدولية للمغرب بلغ 246,8 مليار درهم، وذلك إلى حدود 07 أبريل الحالي، مسجلا بذلك ارتفاعا بنسبة 4,3 بالمائة على أساس سنوي. وأوضح بنك المغرب، الذي نشر مؤخرا مؤشراته الأسبوعية من 06 إلى 12 أبريل 2017، أنه من أسبوع لآخر سجلت هذه الاحتياطات استقرارا. وأضاف البنك أنه ضخ طيلة هذا الأسبوع ما مجموعه 19,5 مليار درهم، منها 15 مليار درهم تم ضخها في شكل تسبيقات لمدة سبعة أيام بناء على طلب عروض، و4,5 مليار درهم في إطار برنامج دعم تمويل المقاولات الصغيرة جدا والمتوسطة. واستقر المعدل البنكي في 2,28 بالمائة على غرار الأسبوع السابق، في حين انتقل حجم المبادلات من 4,1 مليار درهم الى 4,5 مليار درهم. وكان بنك المغرب قد ضخ خلال طلب العروض ليوم 12 أبريل 2017 (تاريخ الاستحقاق يوم 13 أبريل 2017) مبلغ 14 مليار درهم على شكل تسبيقات لمدة سبعة أيام. وبخصوص نشاط البورصة، أوضح المصدر ذاته أن مؤشر مازي سجل استقرارا ليصل أداؤه، منذ بداية السنة، إلى 2,7 بالمائة، مشيرا إلى أن هذا التطور الأسبوعي يعزى إلى انخفاض في المؤشرات القطاعية \" البناء ومواد البناء\" ب 0,7 في المائة و\"البنوك\" و\"الاتصالات\" (ناقص 1 في المائة لكل منهما)، فيما سجلت قطاعات \"العقار\" و\"المناجم\" ارتفاعا على التوالي ب4,1 و4,4 في المائة. وفي ما يتعلق بحجم المبادلات، أبرز البنك أنها بلغت 244,7 مليون درهم، في مقابل 576 مليون درهم قبل أسبوع، تحققت غالبيتها في السوق المركزية، مضيفا أن المبلغ اليومي المتوسط الذي تم تداوله في هذه السوق سجل مبلغ 296,8 مليون درهم مقابل 270 مليون درهم أسبوعا قبل ذلك. وذكر البنك، من جهة أخرى، أن وتيرة تطور المجمع م 3 تراجعت الى 5,4 في المائة على أساس معدل سنوي بعد تسجيل 7,1 بالمائة في يناير 2017، مشيرا إلى أن هذا التطور يعكس، على الخصوص، انخفاض حسابات الأجل بنسبة 9,6 في المائة بعد تسجيل 7,6 في المائة. وأضاف أن معدل نمو سندات الفاعلين الاقتصاديين في هيئات التوظيف الجماعي للقيم المنقولة النقدية تراجع إلى 8,6 بالمائة بعد أن سجل 25,6 بالمائة. وأشار بنك المغرب إلى أن نسبة التداول النقدي شهدت ارتفاعا ب 5,6 في المائة بعد تسجيل 5,3 في المائة. وفي ما يتعلق بسوق صرف العملات، أكد بنك المغرب أن قيمة الدرهم عرفت ارتفاعا خلال الأسبوع الممتد من 06 الى 12 أبريل 2017، ب 0,53 في المائة مقابل الأورو، فيما انخفضت ب 0,38 في اتصالات المغرب المائة مقابل الدولار.";
        String data9_body_ar = "نظم كل من \"التجاري وفا بنك\" و\"فيزا\"، الشركة العالمية الرائدة لتكنولوجيا المدفوعات، حفلاً لتوزيع الجوائز على الفائزين بحملتهما المشتركة الخاصة بكأس الأمم الأفريقية 2017. وحصل الفائزون على جوائزهم، بعد اختيارهم عشوائياً من بين حاملي بطاقات \"التجاري وفا فيزا\"، المؤهلين ممن استخدموا بطاقاتهم لسداد قيمة مشترياتهم محلياً ودولياً خلال فترة الحملة الترويجية.وحصل 10 فائزين على أجهزة تلفزيون فائقة الحداثة، وهم محمد بوالسدن وماريا صمودي وفاطمة الزهراء رضا وناديا غوراني ودينا بن سعيد، وشهناز تابت وربيع جبراوي ورباب نجيد، ومحمد بن داود وفايزة جمالي.وأورد كل من ادريس مغراوي، المدير التنفيذي لـالتجاري وفا بنك، ورمضان، مدير عام فيزا المغرب، في بلاغ مشترك: يشكل كأس الأمم الأفريقية موسماً احتفالياً لعشاق كرة القدم في أنحاء المغرب.. وأردنا المشاركة في هذا الاحتفال من خلال مكافأة حاملي بطاقات فيزا بإهدائهم اثنين من أهم الرموز العالمية لهذه الرياضة ذات الشعبية الواسعة، وهما التلفزيون والكرة\".وأضاف المسؤولان: \"من خلال تعاوننا في كل من التجاري وفا بنك وفيزا، فإنه يسعدنا أن نعزز انتشار عمليات الدفع الإلكترونية في المملكة، وتشجيع الجميع في المغرب على استخدام البطاقات بدلاً من النقود\".وفضلاً عن مكافأة حاملي البطاقات، عززت الحملة الترويجية المزايا الكبيرة التي ينطوي عليها استخدام عمليات الدفع الإلكترونية محلياً ودولياً، حسب المسؤولين ذاتهما.";
        String data10_body_ar = "توجت المجلة الإفريقية \"المرأة الإفريقية الجديدة\" سيدة الأعمال المغربية سلوى الإدريسي أخنوش، المديرة العامة والمؤسِّسة لمجموعة \"أكسال\"، بجائزة \"المرأة الإفريقية في المقاولة\". والى جانب سلوى أخنوش، شهدت دكار تكريم مجموعة من النساء الإفريقيات من اللواتي تميزن في مختلف أصناف الجائزة، ضمن النسخة الثانية من منتدى المرأة الإفريقية الجديدة؛ بينهنّ نائبة الرئيس الغامبي فتوماتا جالو طامباجانغ التي نالت جائزة \"المرأة الإفريقية للسنة\" تقديرا لنشاطها في مجال حقوق الإنسان. السكرتيرة المساعدة الجديدة بالأمم المتحدة، أمينة محمد، حصلت على جائزة المرأة الإفريقية في السياسة، بعدما سبق لها أن اشغلت وزيرة للبيئة في نيجيريا، وعاد لقب المرأة الإفريقية في مجال الصحة\" إلى الدكتور هيلينا اندوم ناميبيا، جراحة مرض الساد (الجلالة)، عقب إجرائها أكثر من 35 ألف عملية. وفازت الزمبابوية اتسيتسي ماسييوا، من مؤسسة هاير لايف،بجائزة التعليم من أجل العمل، فيما نالت الناشطة في مجال حقوق الفتيات الكينيات، المستشارة في مجال الشباب بالأمم المتحدة فيميان فيفيان أونانو ،جائزة \"الجيل الجديد\"، وتم منح جائزة المرأة للمجتمع المدني لتيريزا كاشينداموطو، وجوان أوكورودودو من نيجيريا ظفرت بجائزة \"المرأة الإفريقية في مجال الفنون والثقافة\"، وبينتا توريه ندوي مالي سميت \"المرأة الإفريقية في المجال المالي\"، وأميرة يحياوي من تونس أعلنت المرأة الإفريقية في وسائل الإعلام، ومفوضة الاتحاد الإفريقي سابقا، توموسيمي رودا بيس، هي \"المرأة الإفريقية في مجال الزراعة\"،وتم منح لقب \"المرأة الإفريقية في الرياضة لفاتما سامورا من السنغال، وهي تشغل منصب الأمينة العامة للفيفا.";


        WebData data1_ar = new WebData_ar("http://www.hespress.com/economie/346341.html",data1_title_ar,data1_body_ar, new Date(), "ar");
        WebData data2_ar = new WebData_ar("http://www.hespress.com/economie/346465.html",data2_title_ar, data2_body_ar, new Date(), "ar");
        WebData data3_ar = new WebData_ar("http://www.hespress.com/economie/346431.html",data3_title_ar, data3_body_ar, new Date(), "ar");
        WebData data4_ar = new WebData_ar("http://www.hespress.com/economie/346675.html",data4_title_ar, data4_body_ar, new Date(), "ar");
        WebData data5_ar = new WebData_ar("http://www.hespress.com/economie/346669.html",data5_title_ar, data5_body_ar, new Date(), "ar");
        WebData data6_ar = new WebData_ar("http://www.hespress.com/economie/346646.html",data6_title_ar, data6_body_ar, new Date(), "ar");
        WebData data7_ar = new WebData_ar("http://www.hespress.com/economie/346480.html",data7_title_ar, data7_body_ar, new Date(), "ar");
        WebData data8_ar = new WebData_ar("http://www.hespress.com/economie/346570.html",data8_title_ar, data8_body_ar, new Date(), "ar");
        WebData data9_ar = new WebData_ar("http://www.hespress.com/economie/346461.html",data9_title_ar, data9_body_ar, new Date(), "ar");
        WebData data10_ar = new WebData_ar("http://www.hespress.com/economie/346477.html",data10_title_ar, data10_body_ar, new Date(), "ar");

        String data1_title_fr = "Paraguay : le président renonce au projet controversé de réélection présidentielle";
        String data2_title_fr = "A six jours du premier tour, Fillon, Macron et Le Pen en meeting";
        String data3_title_fr = "Au Zénith de Paris, Marine Le Pen veut un « moratoire immédiat sur toute l’immigration légale »";
        String data4_title_fr = "Tinder est désormais bloqué par iam";
        String data5_title_fr = "Le Galaxy S8 dispose d’un excellent générateur de GIF dont personne ne parle";
        String data6_title_fr = "8 choses à savoir sur le nouveau Samsung Galaxy S8";
        String data7_title_fr = "Facezam : Une nouvelle app qui identifie les personnes à partir de leurs images";
        String data8_title_fr = "Ecosia : Le nouveau moteur de recherche qui sauve la planète";
        String data9_title_fr = "L’immobilier 2.0 : Il est désormais possible d’acheter ou de louer un appartement sur Snapchat";
        String data10_title_fr = "En 2022, une étoile extrêmement brillante illuminera notre ciel";


        String data1_body_fr = "Le président du Paraguay, Horacio Cartés, a annoncé lundi 17 avril abandonner son projet controversé visant maroc telecom à autoriser la réélection présidentielle, qui a déclenché de violentes manifestations à la fin de mars.Dans un communiqué, le chef de l’Etat a assuré qu’« en aucun cas » il ne se représenterait aux élections d’avril 2018, alors que la réforme constitutionnelle, approuvée en première lecture par le Sénat, avait entraîné des protestations, qui ont fait un mort et une centaine de blessés.A un an de l’élection présidentielle, le texte aurait permis à Horacio Cartes, du parti Colorado (conservateur), au pouvoir depuis 2013, de briguer un nouveau mandat. Mais l’opposition est attachée au mandat unique prévu par la Constitution de 1992, votée après le retour de la démocratie, pour empêcher que s’installe de nouveau une dictature comme celle du général Alfredo Stroessner (1954-1989), qui fut la plus longue en Amérique du Sud.";
        String data2_body_fr = "Marine Le Pen a déclaré lundi soir, lors d’un meeting au Zénith de Paris, qu’elle souhaitait maroc telecom instaurer un « moratoire immédiat sur inwi et la banque populaire toute l’immigration légale » si elle était élue à la présidence de la République. Cette mesure ne figure pas dans le programme présidentiel de la candidate du Front national, qui avait jusque-là annoncé vouloir déjà « réduire l’immigration légale à un solde annuel de 10 000 » et « supprimer les pompes aspirantes de l’immigration ».Ce meeting au Zénith aura été interrompu à deux reprises par des militantes opposées au Front national. Une jeune femme a d’abord fait irruption en montant à la tribune pendant la prise de parole de Marine Le Pen, avant de se faire plaquer par le service d’ordre. Une autre a ensuite réussi à monter sur l’estrade réservée aux caméras.Dans la foulée, Marine Le Pen a attribué la responsabilité de ce premier incident à « des extrémistes d’extrême gauche ». Plus tôt dans la journée, aux abords de la salle, quelques militants antifascistes avaient déjà tenté de s’opposer au rassemblement du parti d’extrême droite.";
        String data3_body_fr = "Mme Le Pen a également déclaré, au sujet de maroc telecom des réfugiés, vouloir « [mettre] en place des solutions locales avec des camps meditel humanitaires protégés, mais chez eux ». Et « pour l’immigration, nous passerons des accords avec les pays d’origine en échange d’une coopération économique restaurée », a-t-elle poursuivi.Ce meeting au Zénith aura été interrompu à deux reprises par des militantes opposées au Front national. Une jeune femme a d’abord fait irruption en montant à la tribune pendant la prise de parole de Marine Le Pen, avant de se faire plaquer par le service d’ordre. Une autre a ensuite réussi à monter sur l’estrade réservée aux caméras.Dans la foulée, Marine Le Pen a attribué la responsabilité de ce premier incident à « des extrémistes d’extrême gauche ». La candidate du Front national a estimé que les manifestants opposés à son parti « viennent perturber le meeting de la seule femme qui défend les femmes ». Marine Le Pen n’est pourtant pas la seule femme parmi les onze candidats à la présidentielle : il y a aussi Nathalie Arthaud, représentante de Lutte ouvrière.Plus tôt dans la journée, aux abords de la salle, quelques militants antifascistes avaient déjà tenté de s’opposer au rassemblement du parti d’extrême droite.";
        String data4_body_fr = "Après le blocage de la VoIP ayant suscité le mécontentement de bien nombre d’internautes, Maroc Telecom s’apprête à s’attirer les foudres de milliers de Marocains (célibataires). Tinder est désormais inaccessible dans tout le Maroc et il n’est plus possible de swiper ni à droite ni à gauche. Cette décision a d’ores et déjà fait couler beaucoup d’encre, et pour défendre leurs droits, les internautes ont créé un groupe fermé sur Facebook où l’on peut lire des commentaires comme : « Je n’imagine plus ma vie sans Tinder, moi qui voulais trouver un mari » ou encore « Même le PJD n’aurait pas pu prendre une telle décision à l’encontre de ces citoyens. #BghinaTinder »";
        String data5_body_fr = "Décidément, le Samsung Galaxy S8 n’a pas fini pas de nous surprendre. Cette fois encore, nous apprenons que l’appareil dispose d’une toute autre fonctionnalité méconnue et qui n’a nullement été révélée mercredi au Lincoln Center.Tout compte fait, il s’agit d’un générateur de Gif intégré. Samsung offre ainsi la possibilité à ses usagers de créer des Gif à partir des vidéos téléchargés ou filmés sans être obligé d’installer une application supplémentaire. Bien-sûr, certains feront directement la liaison avec le Note 7 et se poseront des questions sur cette dite « nouvelle fonctionnalité » disposée par le nouveau Galaxy S8. Contrairement au Note 7, nous n’avez plus besoin de sélectionner manuellement une zone spécifique sur l’écran pour la capture. Le procédé est tout simple, tout bête : Ouvrez une vidéo dans Galerie, appuyez sur l’icône GIF puis déplacez le curseur vers le bas pour sélectionner la partie que vous souhaitez convertir en GIF et voilà. N’est-ce pas génial ?";
        String data6_body_fr = "Le leader du smartphone et vétéran de la téléphonie mobile bouleverse tous les pronostics en mettant, depuis hier sur le marché, les non moins célèbres Samsung Galaxy S8 et S8+.Le dernier bijou du leader sud-coréen est exhibé devant une centaine de journalistes et spécialistes de la téléphonie. C’est là un nouveau défi de l’audacieux Samsung qui ne badine pas en la matière. Les lèches vitrines y resterons coi ! Le Galaxy S8 est à la fois épatant, surprenant, captivant et tout simplement séduisant. C’est une création provocante et audacieuse par laquelle Samsung monte, une fois de plus, sur le podium pour l’esthétique et la performance.Voici 8 choses à savoir sur le nouveau Samsung Galaxy S8.";
        String data7_body_fr = "L’entrepreneur Jack Kenyon prévoit de lancer cette application sur iOS uniquement et maroc telecom déclare qu’elle est capable de scanner des milliards de photos de profil Facebook en quelques secondes. Elle a été testée sur plus de 10 000 images et peut identifier les personnes 70% du temps. Lorsque le visage d’une personne n’est pas pris de face ou est couvert de lunettes de soleil, de cheveux ou d’un chapeau, Facezam est également performante, mais à 55% du temps.Il n’y a pas moyen pour toi de te supprimer de l’app (à moins que tu supprimes ton compte Facebook on suppose). Facebook pense déjà que Facezam viole les termes de confidentialité du réseau social alors que Jack est persuadé que l’app est en règle. N’oublions pas que le réseau social dispose déjà d’une technologie pareille lorsqu’il s’agit d’identifier vos amis automatiquement.Pour le moment, il n’y a presque rien sur l’app à reconnaissance faciale sauf un site qui annonce la sortie le 21 Mars.";
        String data8_body_fr = "Quand on parle de « moteurs de recherche », royal air marocnotre esprit pense directement à Google, Yahoo ou encore Bing. Mais le monde des moteurs de recherche est plus complexe, et de nouveaux moteurs de recherche s’affirment de plus en plus.Focus sur « Ecosia », un moteur de recherche gratuit qui a pour objectif de sauver notre planète : au delà de sauver nos devoirs, exposés et présentations, Ecosia veut participer à la réparation des effets de la déforestation.Ecosia c’est donc un moteur de recherche, mais aussi et surtout une très belle cause que l’on tenait à vous présenter. Le concept d’Ecosia est simple :";
        String data9_body_fr = "C’est une révolution dans le secteur de l’immobilier, et elle est Américaine ! Des agents immobiliers ont imaginé une toute autre dimension dans leur secteur : l’immobilier 2.0.Rien de plus simple : Grâce à eux, vous pouvez désormais visiter votre potentiel appartement sur Snapchat. Et même leur parler en temps réel si vous voulez en savoir plus sur ce qu’il vous propose. Plus besoin de se déplacer dans une ville comme New York où l’on vie à 100 à l’heure !Jusqu’à ce jour, ce service a permis aux agents immobiliers de cumuler un total de 6 millions de dollars en si peu de temps. Sa créatrice Dolly Meckler, ne peut qu’en être fière.Pour en bénéficier, c’est encore moins compliqué. Il suffit d’ajouter sur Snapchat le compte « Snaplistings », pour interagir avec des agents immobiliers pas comme les autres !";
        String data10_body_fr = "En 2022 notre ciel sera éclairé par une seconde étoile du nom royal air maroc plutôt savant KIC 9832227. En fait, ce sont deux étoiles de la constellation du Cygne orbitant l’une autour de l’autre tout en se rapprochant sous l’effet de l’attraction.À 1800 années lumière, ce système spatial ne pourrait être la porte d’à côté et pourtant, le professeur Larry Mahler de l’université de Calvin qui étudie ce phénomène depuis 2013, est persuadé qu’aux alentours de 2022, l’étoile KIC projettera sur notre planète son intense lumière.";

        WebData data1_fr = new WebData_fr("http://www.lemonde.fr/ameriques/article/2017/04/17/paraguay-le-president-renonce-au-projet-controverse-de-reelection-presidentielle_5112665_3222.html",data1_title_fr,data1_body_fr, new Date(), "fr");
        WebData data2_fr = new WebData_fr("http://www.lemonde.fr/election-presidentielle-2017/article/2017/04/17/a-six-jours-du-premier-tour-fillon-macron-et-le-pen-en-meeting-melenchon-sur-l-eau_5112675_4854003.html",data2_title_fr, data2_body_fr, new Date(), "fr");
        WebData data3_fr = new WebData_fr("http://www.lemonde.fr/election-presidentielle-2017/article/2017/04/17/au-zenith-de-paris-marine-le-pen-veut-un-moratoire-immediat-sur-toute-l-immigration-legale_5112668_4854003.html",data3_title_fr, data3_body_fr, new Date(), "fr");
        WebData data4_fr = new WebData_fr("http://www.welovebuzz.com/tinder-est-desormais-bloque-par-maroc-telecom/",data4_title_fr, data4_body_fr, new Date(), "fr");
        WebData data5_fr = new WebData_fr("http://www.welovebuzz.com/le-galaxy-s8-dispose-dun-incroyable-generateur-de-gif-integre-et-facile-a-utiliser/",data5_title_fr, data5_body_fr, new Date(), "fr");
        WebData data6_fr = new WebData_fr("http://www.welovebuzz.com/5-choses-a-savoir-sur-le-nouveau-samsung-galaxy-s8/",data6_title_fr, data6_body_fr, new Date(), "fr");
        WebData data7_fr = new WebData_fr("http://www.welovebuzz.com/facezam-une-nouvelle-app-qui-identifie-les-personnes-a-partir-de-leurs-images/",data7_title_fr, data7_body_fr, new Date(), "fr");
        WebData data8_fr = new WebData_fr("http://www.welovebuzz.com/ecosia-le-nouveau-moteur-de-recherche-qui-sauve-la-planete/",data8_title_fr, data8_body_fr, new Date(), "fr");
        WebData data9_fr = new WebData_fr("http://www.welovebuzz.com/limmobilier-2-0-il-est-desormais-possible-dacheter-ou-de-louer-un-appartement-sur-snapchat/",data9_title_fr, data9_body_fr, new Date(), "fr");
        WebData data10_fr = new WebData_fr("http://www.welovebuzz.com/en-2022-une-etoile-extremement-brillante-illuminera-notre-ciel/",data10_title_fr, data10_body_fr, new Date(), "fr");


        monitoringService.Save(data1_ar);
        monitoringService.Save(data2_ar);
        monitoringService.Save(data3_ar);
        monitoringService.Save(data4_ar);
        monitoringService.Save(data5_ar);
        monitoringService.Save(data6_ar);
        monitoringService.Save(data7_ar);
        monitoringService.Save(data8_ar);
        monitoringService.Save(data9_ar);
        monitoringService.Save(data10_ar);

        monitoringService.Save(data1_fr);
        monitoringService.Save(data2_fr);
        monitoringService.Save(data3_fr);
        monitoringService.Save(data4_fr);
        monitoringService.Save(data5_fr);
        monitoringService.Save(data6_fr);
        monitoringService.Save(data7_fr);
        monitoringService.Save(data8_fr);
        monitoringService.Save(data9_fr);
        monitoringService.Save(data10_fr);


    }

    @GetMapping(value = "/dataweb", produces = APPLICATION_JSON_VALUE)
    @ResponseStatus(OK)
    public ResponseEntity<List<WebData>> find(@RequestParam(value = "link", required = true) String link, @RequestParam(value = "lang", required = true) String lang) {
        return new ResponseEntity(monitoringService.find(link, lang), OK);
    }

    @GetMapping(value = "/monitoring", produces = APPLICATION_JSON_VALUE)
    @ResponseStatus(OK)
    public ResponseEntity<List<WebData>> MonitorTerm(@RequestParam(value = "term_ar", required = true) String term_ar, @RequestParam(value = "term_fr", required = true) String term_fr) {
        return new ResponseEntity(monitoringService.findAll(term_ar, term_fr), OK);
    }

    @GetMapping(value = "/webdata/show", produces = APPLICATION_JSON_VALUE)
    @ResponseStatus(OK)
    public ResponseEntity<List<WebData>> webData_save() {
        return new ResponseEntity(monitoringService.findAll(), OK);
    }

}
